### PR TITLE
add 'it' support

### PR DESCRIPTION
**Pull request by rubinoneroweb**
Added support for italian language.

### CODE REVIEW

**Comment by aliibrahim** [comment]
@rubinoneroweb Please update Readme as well!

**Comment by rubinoneroweb** [comment]
There, I updated the readme file. Should I do a new pull request now? Please be patient with me as it's my first contribution to a project in github and I'm feeling a bit nervous since I'm afraid of doing someting wrong :(

**Comment by aliibrahim** [comment]
Please do it on the same pull request.

**Comment by rubinoneroweb** [comment]
ok i committed the change to the readme to the same branch.

**Comment by aliibrahim** [comment]
The changes are not there. They should be in the same merge request here.

**Comment by rubinoneroweb** [comment]
I don't know what happened but the translation had vanished :|
Now i committed them back, everything should be in order.
thank you for your patience.

**Comment by aliibrahim** [comment]
:+1: Merging now!

**Pull request merged**
